// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const IconRadixIconsCross1: typeof import('~icons/radix-icons/cross1.jsx')['default'];
  const IconRadixIconsHamburgerMenu: typeof import('~icons/radix-icons/hamburger-menu.jsx')['default'];
}
export {};
